var SeqPatterns = [{
	instrument: SeqInstruments.Drum78,
	p: [
	{ what: SeqDrumSound.BD, when: 1 },
	{ what: SeqDrumSound.OH, when: 1 },
	{ what: SeqDrumSound.CH, when: 2 },
	{ what: SeqDrumSound.CH, when: 3 },
	{ what: SeqDrumSound.CH, when: 4 },
	{ what: SeqDrumSound.SD, when: 5 },
	{ what: SeqDrumSound.CH, when: 6 },
	{ what: SeqDrumSound.CH, when: 7 },
	{ what: SeqDrumSound.CH, when: 8 },
	{ what: SeqDrumSound.BD, when: 9 },
	{ what: SeqDrumSound.OH, when: 9 },
	{ what: SeqDrumSound.CH, when: 10 },
	{ what: SeqDrumSound.CH, when: 11 },
	{ what: SeqDrumSound.CH, when: 12 },
	{ what: SeqDrumSound.SD, when: 13 },
	{ what: SeqDrumSound.CH, when: 14 },
	{ what: SeqDrumSound.CH, when: 15 },
	{ what: SeqDrumSound.CH, when: 16 },
	{ what: SeqDrumSound.BD, when: 17 },
	{ what: SeqDrumSound.OH, when: 17 },
	{ what: SeqDrumSound.CH, when: 18 },
	{ what: SeqDrumSound.CH, when: 19 },
	{ what: SeqDrumSound.CH, when: 20 },
	{ what: SeqDrumSound.SD, when: 21 },
	{ what: SeqDrumSound.CH, when: 22 },
	{ what: SeqDrumSound.CH, when: 23 },
	{ what: SeqDrumSound.CH, when: 24 },
	{ what: SeqDrumSound.BD, when: 25 },
	{ what: SeqDrumSound.OH, when: 25 },
	{ what: SeqDrumSound.CH, when: 26 },
	{ what: SeqDrumSound.CH, when: 27 },
	{ what: SeqDrumSound.CH, when: 28 },
	{ what: SeqDrumSound.SD, when: 29 },
	{ what: SeqDrumSound.CH, when: 30 },
	{ what: SeqDrumSound.CH, when: 31 },
	{ what: SeqDrumSound.CH, when: 32 },
	]
},
{
	instrument: SeqInstruments.BluePlanet,
	p: [
	{ what: "D#", when: 1 },
	{ what: "C", when: 1 },
	{ what: "G#", when: 1 },
	{ what: "D#", when: 17 },
	{ what: "C", when: 17 },
	{ what: "G", when: 17 },
	]
},
{
	instrument: SeqInstruments.Bassline,
	p: [
	{ what: "D#", when: 1 },
	{ what: "C", when: 2 },
	{ what: "G#", when: 3 },
	{ what: "D#", when: 4 },
	{ what: "C", when: 5 },
	{ what: "G#", when: 6 },
	{ what: "C", when: 7 },
	{ what: "C", when: 8 },
	{ what: "G#", when: 9 },
	{ what: "D#", when: 10 },
	{ what: "C", when: 11 },
	{ what: "G#", when: 12 },
	{ what: "D#", when: 13 },
	{ what: "C", when: 14 },
	{ what: "G#", when: 15 },
	{ what: "G#", when: 16 },
	{ what: "D#", when: 17 },
	{ what: "C", when: 18 },
	{ what: "G#", when: 19 },
	{ what: "D#", when: 20 },
	{ what: "C", when: 21 },
	{ what: "G", when: 22 },
	{ what: "D#", when: 23 },
	{ what: "A#", when: 24 },
	{ what: "G", when: 25 },
	{ what: "G", when: 26 },
	{ what: "G", when: 27 },
	{ what: "G", when: 28 },
	{ what: "F", when: 29 },
	{ what: "D#", when: 30 },
	{ what: "G", when: 31 },
	{ what: "C", when: 32 },
	]
}
];
